# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.getroxanne.com
title: Roxanne
email: contact@getroxanne.com
author: Roxanne Team
description: > # 
  Roxanne is your AI dating communication coach, helping thoughtful adults navigate 
  modern dating with confidence, authenticity, and emotional intelligence.
copyright: 'Copyright &copy; 2024 A Million Dreams LLC. All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/getroxanne
    icon: fa-brands fa-twitter
  - title: instagram
    url: https://instagram.com/getroxanne
    icon: fa-brands fa-instagram
  - title: tiktok
    url: https://tiktok.com/@getroxanne
    icon: fa-brands fa-tiktok
