# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.getroxanne.com
title: Roxanne
description: "Roxanne is your AI dating communication coach, helping thoughtful adults navigate modern dating with confidence, authenticity, and emotional intelligence."
author: Roxanne Team
email: contact@getroxanne.com
copyright: '© 2025 A Million Dreams LLC. All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Twitter
    url: https://twitter.com/getroxanne
    icon: fa-brands fa-twitter
  - title: Instagram
    url: https://instagram.com/get_roxanne
    icon: fa-brands fa-instagram
  - title: TikTok
    url: https://tiktok.com/@getroxanne
    icon: fa-brands fa-tiktok
